
-- CREATE TABLE raw_fannie (
-- 	-- index BIGINT, 
-- 	reference_pool_id FLOAT(53), 
-- 	loan_id BIGINT, 
-- 	monthly_reporting_period BIGINT, 
-- 	channel TEXT, 
-- 	seller_name TEXT, 
-- 	servicer_name TEXT, 
-- 	master_servicer FLOAT(53), 
-- 	original_interest_rate FLOAT(53), 
-- 	current_interest_rate FLOAT(53), 
-- 	original_upb FLOAT(53), 
-- 	upb_at_issuance FLOAT(53), 
-- 	current_actual_upb FLOAT(53), 
-- 	original_loan_term BIGINT, 
-- 	origination_date BIGINT, 
-- 	first_payment_date BIGINT, 
-- 	loan_age FLOAT(53), 
-- 	remaining_months_to_legal_maturity FLOAT(53), 
-- 	remaining_months_to_maturitry FLOAT(53), 
-- 	maturity_date FLOAT(53), 
-- 	oltv BIGINT, 
-- 	ocltv BIGINT, 
-- 	number_of_borrowers BIGINT, 
-- 	dti BIGINT, 
-- 	borrower_credit_score_at_origination BIGINT, 
-- 	coborrower_credit_score_at_origination FLOAT(53), 
-- 	first_time_buyer_flag TEXT, 
-- 	loan_purpose TEXT, 
-- 	property_type TEXT, 
-- 	number_of_units BIGINT, 
-- 	occupancy_status TEXT, 
-- 	property_state TEXT, 
-- 	msa BIGINT, 
-- 	zip_code_short BIGINT, 
-- 	mortgage_insurance_pct FLOAT(53), 
-- 	amortization_type TEXT, 
-- 	prepayment_penalty_indicator TEXT, 
-- 	interest_only_indicator TEXT, 
-- 	interest_only_first_prin_and_int_pay_dt FLOAT(53), 
-- 	months_to_amortization FLOAT(53), 
-- 	current_loan_delinq_status TEXT, 
-- 	loan_payment_history TEXT, 
-- 	modification_flag TEXT, 
-- 	mortgage_insurance_cancellation_indicator FLOAT(53), 
-- 	zero_balance_code FLOAT(53), 
-- 	zero_balance_effective_date FLOAT(53), 
-- 	upb_at_time_of_removal FLOAT(53), 
-- 	repurchase_date FLOAT(53), 
-- 	scheduled_principcal_current FLOAT(53), 
-- 	total_principal_current FLOAT(53), 
-- 	unscheduled_principal_current FLOAT(53), 
-- 	last_paid_installment_date FLOAT(53), 
-- 	foreclosure_date FLOAT(53), 
-- 	disposition_date FLOAT(53), 
-- 	foreclosure_costs FLOAT(53), 
-- 	property_preservation_and_repair_costs FLOAT(53), 
-- 	asset_recovery_costs FLOAT(53), 
-- 	misc_holding_expenses_and_credit FLOAT(53), 
-- 	associated_taxes_for_holding_property FLOAT(53), 
-- 	net_sales_proceeds FLOAT(53), 
-- 	credit_enhancement_proceeds FLOAT(53), 
-- 	repurchase_make_whole_proceeds FLOAT(53), 
-- 	other_foreclosure_proceeds FLOAT(53), 
-- 	non_interest_bearing_upb FLOAT(53), 
-- 	principal_forgiveness_amount FLOAT(53), 
-- 	original_list_start_date FLOAT(53), 
-- 	original_list_price FLOAT(53), 
-- 	current_list_start_date FLOAT(53), 
-- 	current_list_price FLOAT(53), 
-- 	borrower_credit_score_at_issuance FLOAT(53), 
-- 	coborrower_credit_score_at_issuance FLOAT(53), 
-- 	borrower_credit_score_current FLOAT(53), 
-- 	coborrower_credit_score_current FLOAT(53), 
-- 	mortgage_insurance_type FLOAT(53), 
-- 	servicing_activity_indicator TEXT, 
-- 	current_period_modification_loss_amount FLOAT(53), 
-- 	cumulative_modification_loss_amount FLOAT(53), 
-- 	current_period_credit_event_net_gain_or_loss FLOAT(53), 
-- 	cumulative_credit_event_net_gain_or_loss FLOAT(53), 
-- 	home_ready_program_indicator FLOAT(53),
-- 	foreclosure_principcal_write_off_amount FLOAT(53), 
-- 	relocation_mortgage_indicator TEXT, 
-- 	zero_balance_code_change_date FLOAT(53), 
-- 	loan_holdback_indicator FLOAT(53), 
-- 	loan_holdback_effective_date FLOAT(53), 
-- 	delinquent_accrued_interest FLOAT(53), 
-- 	property_valuation_method FLOAT(53), 
-- 	high_balance_loan_indicator TEXT, 
-- 	arm_init_fixed_rate_period_5yr FLOAT(53), 
-- 	arm_product_type FLOAT(53), 
-- 	initial_fixed_rate_period FLOAT(53), 
-- 	interest_rate_adj_freq FLOAT(53), 
-- 	next_interest_rate_adj_date FLOAT(53), 
-- 	next_payment_change_date FLOAT(53), 
-- 	index_col FLOAT(53), 
-- 	arm_cap_structure FLOAT(53), 
-- 	initial_interest_rate_cap_up_pct FLOAT(53), 
-- 	periodic_interest_rate_cap_up_pct FLOAT(53), 
-- 	lifetime_interest_rate_cap_up_pct FLOAT(53), 
-- 	mortgage_margin FLOAT(53), 
-- 	arm_balloon_indicator FLOAT(53), 
-- 	arm_plan_number FLOAT(53), 
-- 	borrower_assistance_plan FLOAT(53), 
-- 	hltv_refi_option_indicator TEXT, 
-- 	deal_name FLOAT(53), 
-- 	repurchase_make_whole_proceeds_flag TEXT, 
-- 	alternative_delinq_resolution FLOAT(53), 
-- 	alternative_delinq_resolution_count FLOAT(53), 
-- 	total_deferral_amount FLOAT(53)
-- )



CREATE TABLE raw_fannie (
    reference_pool_id text,
  loan_id text,
  monthly_reporting_period text,
  channel text,
  seller_name text,
  servicer_name text,
  master_servicer text,
  original_interest_rate numeric,
  current_interest_rate numeric,
  original_upb numeric,
  upb_at_issuance numeric,
  current_actual_upb numeric,
  original_loan_term numeric,
  origination_date text,
  first_payment_date text,
  loan_age numeric,
  remaining_months_to_legal_maturity numeric,
  remaining_months_to_maturitry numeric,
  maturity_date text,
  oltv numeric,
  ocltv numeric,
  number_of_borrowers numeric,
  dti numeric,
  borrower_credit_score_at_origination numeric,
  coborrower_credit_score_at_origination numeric,
  first_time_buyer_flag text,
  loan_purpose text,
  property_type text,
  number_of_units numeric,
  occupancy_status text,
  property_state text,
  msa text,
  zip_code_short text,
  mortgage_insurance_pct numeric,
  amortization_type text,
  prepayment_penalty_indicator text,
  interest_only_indicator text,
  interest_only_first_prin_and_int_pay_dt text,
  months_to_amortization integer,
  current_loan_delinq_status text,
  loan_payment_history text,
  modification_flag text,
  mortgage_insurance_cancellation_indicator text,
  zero_balance_code text,
  zero_balance_effective_date text,
  upb_at_time_of_removal numeric,
  repurchase_date text,
  scheduled_principcal_current numeric,
  total_principal_current numeric,
  unscheduled_principal_current numeric,
  last_paid_installment_date text,
  foreclosure_date text,
  disposition_date text,
  foreclosure_costs numeric,
  property_preservation_and_repair_costs numeric,
  asset_recovery_costs numeric,
  misc_holding_expenses_and_credit numeric,
  associated_taxes_for_holding_property numeric,
  net_sales_proceeds numeric,
  credit_enhancement_proceeds numeric,
  repurchase_make_whole_proceeds numeric,
  other_foreclosure_proceeds numeric,
  non_interest_bearing_upb numeric,
  principal_forgiveness_amount numeric,
  original_list_start_date text,
  original_list_price numeric,
  current_list_start_date text,
  current_list_price numeric,
  borrower_credit_score_at_issuance numeric,
  coborrower_credit_score_at_issuance numeric,
  borrower_credit_score_current numeric,
  coborrower_credit_score_current numeric,
  mortgage_insurance_type text,
  servicing_activity_indicator text,
  current_period_modification_loss_amount numeric,
  cumulative_modification_loss_amount numeric,
  current_period_credit_event_net_gain_or_loss numeric,
  cumulative_credit_event_net_gain_or_loss numeric,
  home_ready_program_indicator text,
  foreclosure_principcal_write_off_amount numeric,
  relocation_mortgage_indicator text,
  zero_balance_code_change_date text,
  loan_holdback_indicator text,
  loan_holdback_effective_date text,
  delinquent_accrued_interest numeric,
  property_valuation_method text,
  high_balance_loan_indicator text,
  arm_init_fixed_rate_period_5yr text,
  arm_product_type text,
  initial_fixed_rate_period numeric,
  interest_rate_adj_freq numeric,
  next_interest_rate_adj_date text,
  next_payment_change_date text,
  index_col text,
  arm_cap_structure text,
  initial_interest_rate_cap_up_pct numeric,
  periodic_interest_rate_cap_up_pct numeric,
  lifetime_interest_rate_cap_up_pct numeric,
  mortgage_margin numeric,
  arm_balloon_indicator text,
  arm_plan_number numeric,
  borrower_assistance_plan text,
  hltv_refi_option_indicator text,
  deal_name text,
  repurchase_make_whole_proceeds_flag text,
  alternative_delinq_resolution text,
  alternative_delinq_resolution_count numeric,
  total_deferral_amount numeric
);


CREATE TABLE fannie_processed (
  reference_pool_id text,
  loan_id text,
  monthly_reporting_period date,
  channel text,
  seller_name text,
  servicer_name text,
  master_servicer text,
  original_interest_rate numeric,
  current_interest_rate numeric,
  original_upb numeric,
  upb_at_issuance numeric,
  current_actual_upb numeric,
  original_loan_term numeric,
  origination_date date,
  first_payment_date date,
  loan_age numeric,
  remaining_months_to_legal_maturity numeric,
  remaining_months_to_maturitry numeric,
  maturity_date date,
  oltv numeric,
  ocltv numeric,
  number_of_borrowers numeric,
  dti numeric,
  borrower_credit_score_at_origination numeric,
  coborrower_credit_score_at_origination numeric,
  first_time_buyer_flag text,
  loan_purpose text,
  property_type text,
  number_of_units numeric,
  occupancy_status text,
  property_state text,
  msa text,
  zip_code_short text,
  mortgage_insurance_pct numeric,
  amortization_type text,
  prepayment_penalty_indicator text,
  interest_only_indicator text,
  interest_only_first_prin_and_int_pay_dt date,
  months_to_amortization integer,
  current_loan_delinq_status text,
  loan_payment_history text,
  modification_flag text,
  mortgage_insurance_cancellation_indicator text,
  zero_balance_code text,
  zero_balance_effective_date date,
  upb_at_time_of_removal numeric,
  repurchase_date date,
  scheduled_principcal_current numeric,
  total_principal_current numeric,
  unscheduled_principal_current numeric,
  last_paid_installment_date date,
  foreclosure_date date,
  disposition_date date,
  foreclosure_costs numeric,
  property_preservation_and_repair_costs numeric,
  asset_recovery_costs numeric,
  misc_holding_expenses_and_credit numeric,
  associated_taxes_for_holding_property numeric,
  net_sales_proceeds numeric,
  credit_enhancement_proceeds numeric,
  repurchase_make_whole_proceeds numeric,
  other_foreclosure_proceeds numeric,
  non_interest_bearing_upb numeric,
  principal_forgiveness_amount numeric,
  original_list_start_date date,
  original_list_price numeric,
  current_list_start_date date,
  current_list_price numeric,
  borrower_credit_score_at_issuance numeric,
  coborrower_credit_score_at_issuance numeric,
  borrower_credit_score_current numeric,
  coborrower_credit_score_current numeric,
  mortgage_insurance_type text,
  servicing_activity_indicator text,
  current_period_modification_loss_amount numeric,
  cumulative_modification_loss_amount numeric,
  current_period_credit_event_net_gain_or_loss numeric,
  cumulative_credit_event_net_gain_or_loss numeric,
  home_ready_program_indicator text,
  foreclosure_principcal_write_off_amount numeric,
  relocation_mortgage_indicator text,
  zero_balance_code_change_date date,
  loan_holdback_indicator text,
  loan_holdback_effective_date date,
  delinquent_accrued_interest numeric,
  property_valuation_method text,
  high_balance_loan_indicator text,
  arm_init_fixed_rate_period_5yr text,
  arm_product_type text,
  initial_fixed_rate_period numeric,
  interest_rate_adj_freq numeric,
  next_interest_rate_adj_date date,
  next_payment_change_date date,
  index_col text,
  arm_cap_structure text,
  initial_interest_rate_cap_up_pct numeric,
  periodic_interest_rate_cap_up_pct numeric,
  lifetime_interest_rate_cap_up_pct numeric,
  mortgage_margin numeric,
  arm_balloon_indicator text,
  arm_plan_number numeric,
  borrower_assistance_plan text,
  hltv_refi_option_indicator text,
  deal_name text,
  repurchase_make_whole_proceeds_flag text,
  alternative_delinq_resolution text,
  alternative_delinq_resolution_count numeric,
  total_deferral_amount numeric
);

-- CREATE INDEX idx_loan_id_monthly_raw ON raw_fannie (loan_id, monthly_reporting_period DESC);
CREATE INDEX idx_loan_id_monthly ON fannie_processed (loan_id, monthly_reporting_period DESC);

CREATE OR REPLACE FUNCTION cpr(numeric) RETURNS numeric
  AS 'SELECT (1.0 - pow(1.0 - $1, 12)) * 100'
  LANGUAGE SQL
  IMMUTABLE
  RETURNS NULL ON NULL INPUT;

CREATE TABLE agencies (
  id integer primary key,
  name varchar
);

INSERT INTO agencies VALUES (0, 'Fannie Mae'), (1, 'Freddie Mac');

CREATE TABLE servicers (
  id serial primary key,
  name text
);
CREATE UNIQUE INDEX index_servicers_on_name ON servicers (name);


CREATE TABLE hpi_indexes (
  id integer primary key,
  name varchar not null,
  type varchar not null,
  first_date date not null
);

CREATE TABLE hpi_values (
  hpi_index_id integer not null,
  date date not null,
  hpi numeric not null,
  primary key (hpi_index_id, date)
);

CREATE TABLE mortgage_rates (
  month date primary key,
  rate_30_year numeric,
  points_30_year numeric,
  zero_point_rate_30_year numeric,
  rate_15_year numeric,
  points_15_year numeric,
  zero_point_rate_15_year numeric
);

CREATE TABLE raw_msa_county_mappings (
  cbsa_code integer,
  msad_code integer,
  csa_code integer,
  cbsa_name varchar,
  msa_type varchar,
  msad_name varchar,
  csa_name varchar,
  county varchar,
  state varchar,
  state_fips integer,
  county_fips integer,
  county_type varchar,
  state_abbreviation varchar
);

CREATE UNIQUE INDEX idx_raw_msa_mapping ON raw_msa_county_mappings (cbsa_code, msad_code, state_fips, county_fips);



-- Immediately Index on month
-- CREATE INDEX tmp_idx_monthly ON monthly_observations_raw_fannie (loan_sequence_number, reporting_period DESC);
