DROP FUNCTION IF EXISTS cpr(numeric);
DROP TABLE IF EXISTS raw_fannie;
DROP TABLE IF EXISTS fannie_processed;
DROP TABLE IF EXISTS agencies;
DROP TABLE IF EXISTS servicers;
DROP TABLE IF EXISTS hpi_indexes;
DROP TABLE IF EXISTS hpi_values;
DROP TABLE IF EXISTS mortgage_rates;
DROP TABLE IF EXISTS raw_msa_county_mappings;