# DATABASE ADMIN Image Build Stage
FROM python:latest as START

ADD . /tycho
WORKDIR /tycho

RUN apt-get update
RUN apt-get install -y build-essential redis-server sqlite3 curl software-properties-common
RUN pip3 install -r requirements.txt